server:
  server_id: "router_3"
  name: "Routing Server 3"
  tunnel_id: 1003
  bind_address: "::"
  bind_port: 51820
  internal_ip: "192.168.3.253"
  external_ip: "2001:da8:205:2060::c0a8:3fd"
  egress_interface: "wan0"
  log_file: "/var/log/routing_server_3.log"

network_controller:
  url: "http://211.71.65.211:8090"

tunnel:
  psk: "yUoLV+/1yaAeSGxCY/fRHIm1qb3oi4KSP57sRtB3WxE="
  interface_name: "tun0"
  tun_ipv4: "10.10.3.1"
  tun_ipv6: "fd00:100::3"

load_balancer:
  url: "http://8.146.198.12:8080"

metrics:
  report_interval: 10
